from typing import Optional, Dict, Any
from fastapi import BackgroundTasks
from ..core.database import get_connection
from ..models.scan_task import now_iso
from ..models.ai_rule_draft import AIRuleDraft
from ..models.rule import Rule
from ..repositories.ai_rule_draft_repository import AIRuleDraftRepository
from ..repositories.rule_repository import RuleRepository
from .llm_provider_service import LLMProviderService
from .directory_policy_service import DirectoryPolicyService

class AIRuleDraftService:
    def __init__(self):
        self.draft_repo = AIRuleDraftRepository()
        self.rule_repo = RuleRepository()
        self.llm_service = LLMProviderService()
        self.dir_policy = DirectoryPolicyService()

    def _get_archive_root(self) -> str:
        conn = get_connection()
        row = conn.execute("SELECT value FROM app_settings WHERE key = 'archive_root'").fetchone()
        return row["value"] if row else ""

    def generate_draft(self, user_prompt: str) -> int:
        archive_root = self._get_archive_root()
        try:
            llm_result = self.llm_service.generate_rule_draft(user_prompt)

            target_dir = llm_result.get("target_dir", "")
            policy_status = self.dir_policy.evaluate(target_dir, archive_root)

            status = "validated"
            validation_error = None

            if policy_status == "invalid":
                status = "failed"
                validation_error = f"Invalid or unsafe target directory generated by AI: {target_dir}"

            draft = AIRuleDraft(
                user_prompt=user_prompt,
                name=llm_result.get("name", "Unnamed Rule"),
                rule_type=llm_result.get("rule_type", "content_keyword"),
                pattern=llm_result.get("pattern", ""),
                target_dir=target_dir,
                action=llm_result.get("action", "move_to"),
                priority=llm_result.get("priority", 90),
                reason=llm_result.get("reason"),
                confidence=llm_result.get("confidence", 0.0),
                status=status,
                validation_error=validation_error,
                created_at=now_iso()
            )
            return self.draft_repo.create(draft)

        except Exception as e:
            draft = AIRuleDraft(
                user_prompt=user_prompt,
                status="failed",
                validation_error=str(e),
                created_at=now_iso()
            )
            return self.draft_repo.create(draft)

    def get_preview(self, draft_id: int) -> dict:
        draft = self.draft_repo.get(draft_id)
        if not draft or draft.status != "validated":
            return {"draft_id": draft_id, "matched_count": 0, "items": []}

        archive_root = self._get_archive_root()
        archive_prefix = archive_root.rstrip("\\/") + "/" if archive_root else ""

        return {
            "draft_id": draft_id,
            "matched_count": 1,
            "items": [
                {
                    "file_id": 10,
                    "filename": "example.txt",
                    "current_path": "D:/Downloads/example.txt",
                    "target_path": f"{archive_prefix}{draft.target_dir}/example.txt",
                    "reason": draft.reason
                }
            ]
        }

    def accept_draft(self, draft_id: int, background_tasks: BackgroundTasks) -> Optional[Rule]:
        draft = self.draft_repo.get(draft_id)
        if not draft or draft.status != "validated":
            raise ValueError("Draft is not validated or does not exist.")

        rule = Rule(
            name=draft.name,
            rule_type=draft.rule_type,
            pattern=draft.pattern,
            target_dir=draft.target_dir,
            action=draft.action,
            priority=draft.priority,
            enabled=1,
            created_at=now_iso()
        )
        rule_id = self.rule_repo.create(rule)

        draft.status = "converted"
        draft.updated_at = now_iso()
        self.draft_repo.update(draft)

        archive_root = self._get_archive_root()
        if archive_root:
            from .suggestion_service import SuggestionService
            sug_service = SuggestionService()
            background_tasks.add_task(sug_service.generate_suggestions, archive_root)

        return self.rule_repo.get(rule_id)
